-- Insertion du plan comptable SYSCOHADA
INSERT INTO public.chart_of_accounts (account_number, account_name, account_type, is_active) VALUES
('101', 'Capital social', 'Classe 1 – Capitaux', true),
('162', 'Emprunts auprès des établissements de crédit', 'Classe 1 – Capitaux (Dettes financières)', true),
('2334', 'Barrages, digues (aménagements marais salants)', 'Classe 2 – Immobilisation corporelle', true),
('2411', 'Matériel industriel (broyage, lavage, iodation)', 'Classe 2 – Immobilisation corporelle', true),
('2412', 'Outillage industriel (balance, testeur)', 'Classe 2 – Immobilisation corporelle', true),
('2421', 'Matériel agricole (tracteurs, motopompes)', 'Classe 2 – Immobilisation corporelle', true),
('2442', 'Matériel informatique', 'Classe 2 – Immobilisation corporelle', true),
('2444', 'Mobilier de bureau', 'Classe 2 – Immobilisation corporelle', true),
('2451', 'Matériel automobile (camion)', 'Classe 2 – Immobilisation corporelle', true),
('331', 'Matières consommables', 'Classe 3 – Stocks', true),
('332', 'Fournitures d''atelier et d''usine (EPI, petits outils)', 'Classe 3 – Stocks', true),
('334', 'Fournitures de bureau', 'Classe 3 – Stocks', true),
('3351', 'Emballages perdus (sacs)', 'Classe 3 – Stocks', true),
('5211', 'Banque en monnaie nationale', 'Classe 5 – Trésorerie', true),
('5215', 'Banque en devises', 'Classe 5 – Trésorerie', true),
('531', 'Caisse', 'Classe 5 – Trésorerie', true),
('552', 'Monnaie électronique – téléphone portable (Wave, OM)', 'Classe 5 – Trésorerie', true),
('555', 'Autres comptes de trésorerie interne', 'Classe 5 – Trésorerie', true),
('611', 'Électricité', 'Classe 6 – Charges d''exploitation', true),
('612', 'Eau', 'Classe 6 – Charges d''exploitation', true),
('613', 'Transport', 'Classe 6 – Charges d''exploitation', true),
('615', 'Entretien et réparations (maintenance)', 'Classe 6 – Charges d''exploitation', true),
('616', 'Télécommunications (téléphone, internet)', 'Classe 6 – Charges d''exploitation', true),
('618', 'Publicité, foires, communication, marketing', 'Classe 6 – Charges d''exploitation', true),
('61xx', 'Loyers (bureaux, marais salants)', 'Classe 6 – Charges d''exploitation', true),
('64', 'Charges de personnel (salaires, journaliers, contractuels)', 'Classe 6 – Charges de personnel', true),
('661', 'Charges d''intérêts', 'Classe 6 – Charges financières', true),
('68', 'Dotations aux amortissements', 'Classe 6 – Charges calculées', true),
('701', 'Ventes de produits finis – marché local', 'Classe 7 – Produits (CA local)', true),
('702', 'Ventes de produits finis – export', 'Classe 7 – Produits (CA export)', true),
('703', 'Ventes de marchandises (activité commerciale)', 'Classe 7 – Produits', true),
('708', 'Produits accessoires', 'Classe 7 – Produits', true),
('71', 'Production stockée (variation de stock)', 'Classe 7 – Produits d''exploitation', true);