
-- Compléter les comptes de la Classe 9 (Engagements hors bilan) selon SYSCOHADA révisé
-- Ne pas insérer si les comptes existent déjà
INSERT INTO chart_of_accounts (tenant_id, account_number, account_name, account_type, is_active)
SELECT t.id, v.account_number, v.account_name, 'Engagements', true
FROM tenants t
CROSS JOIN (VALUES
  ('9011', 'CREDITS CONFIRMES OBTENUS'),
  ('9012', 'EMPRUNTS RESTANT A ENCAISSER'),
  ('9013', 'FACILITES DE FINANCEMENT RENOUVELABLES'),
  ('9014', 'FACILITES D''EMISSION'),
  ('9018', 'AUTRES ENGAGEMENTS DE FINANCEMENT OBTENUS'),
  ('9021', 'AVALS OBTENUS'),
  ('9022', 'CAUTIONS, GARANTIES OBTENUES'),
  ('9023', 'HYPOTHEQUES OBTENUES'),
  ('9024', 'EFFETS ENDOSSES PAR DES TIERS'),
  ('9028', 'AUTRES GARANTIES OBTENUES'),
  ('9031', 'ACHATS DE MARCHANDISES A TERME'),
  ('9032', 'ACHATS A TERME DE DEVISES'),
  ('9033', 'COMMANDES FERMES DES CLIENTS'),
  ('9038', 'AUTRES ENGAGEMENTS RECIPROQUES OBTENUS'),
  ('9041', 'ABANDONS DE CREANCES CONDITIONNELS'),
  ('9043', 'VENTES AVEC CLAUSE DE RESERVE DE PROPRIETE'),
  ('9048', 'DIVERS ENGAGEMENTS OBTENUS'),
  ('9051', 'CREDITS ACCORDES NON DECAISSES'),
  ('9058', 'AUTRES ENGAGEMENTS DE FINANCEMENT ACCORDES'),
  ('9061', 'AVALS ACCORDES'),
  ('9062', 'CAUTIONS, GARANTIES ACCORDEES'),
  ('9063', 'HYPOTHEQUES ACCORDEES'),
  ('9064', 'EFFETS ENDOSSES PAR L''ENTITE'),
  ('9068', 'AUTRES GARANTIES ACCORDEES'),
  ('9071', 'VENTES DE MARCHANDISES A TERME'),
  ('9072', 'VENTES A TERME DE DEVISES'),
  ('9073', 'COMMANDES FERMES AUX FOURNISSEURS'),
  ('9078', 'AUTRES ENGAGEMENTS RECIPROQUES ACCORDES'),
  ('9081', 'ANNULATIONS CONDITIONNELLES DE DETTES'),
  ('9082', 'ENGAGEMENTS DE RETRAITE'),
  ('9083', 'ACHATS AVEC CLAUSE DE RESERVE DE PROPRIETE'),
  ('9088', 'DIVERS ENGAGEMENTS ACCORDES')
) AS v(account_number, account_name)
WHERE NOT EXISTS (
  SELECT 1 FROM chart_of_accounts coa 
  WHERE coa.tenant_id = t.id AND coa.account_number = v.account_number
);
