// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlcpvyqjvztjtbzijygg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsY3B2eXFqdnp0anRiemlqeWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzMyMDksImV4cCI6MjA2NzkwOTIwOX0.C02KOUMxzRX8LXZ4he9_Va119QaCxQGvf5j800aAU7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});